/* 曲の記録を入口に、連絡・資料・実績を同じ操作で扱う。 */
const WF=ShinkouWorkflow,WC=ShinkouConnections;
const wfValue=id=>document.getElementById(id)?.value||'';
function wfSelect(label,id,options,value){return '<label class="quick-field">'+esc(label)+'<select class="inp" id="'+id+'" aria-label="'+esc(label)+'">'+options.map(([v,l])=>'<option value="'+esc(v)+'" '+(v===value?'selected':'')+'>'+esc(l)+'</option>').join('')+'</select></label>'}
function wfArea(label,id,value,rows=5){return '<label class="quick-field">'+esc(label)+'<textarea class="inp" id="'+id+'" rows="'+rows+'">'+esc(value||'')+'</textarea></label>'}
function wfRow(id,title,sub=''){return '<button class="workflow-row" data-workflow="'+esc(id)+'"><span><b>'+esc(title)+'</b>'+(sub?'<small>'+esc(sub)+'</small>':'')+'</span><span aria-hidden="true">›</span></button>'}
function wfLinks(rows){return rows.map(x=>wfRow(...x)).join('')}
function wfWire(actions){document.getElementById('s3Body').querySelectorAll('[data-workflow]').forEach(b=>b.onclick=()=>actions[b.dataset.workflow]?.())}
function wfGuard(s,initial){if(RO||!S.songs.includes(s)||initial!==JSON.stringify(s.workflow||{})){toast('記録が更新されています。開き直して確認してください');return false}return true}
function wfSetup(){WC.setup({...S.settings.connections,demo:DEMO,readOnly:RO})}
function workflowToday(list){if(RO)return '';const rows=WF.priorities(list,productionReport,D.today());return '<section class="workflow-today" id="workflowToday"><details class="workflow-today-fold"><summary><b>今日確認すること</b><small>'+rows.length+'件を確認 <span aria-hidden="true">⌄</span></small></summary>'+(rows.length?rows.map((a,i)=>'<button class="workflow-priority" data-workflow-priority="'+i+'" data-wf-song="'+esc(a.songId)+'" data-wf-type="'+a.type+'" data-wf-key="'+esc(a.id)+'"><span class="workflow-number">'+(i+1)+'</span><span><small>'+esc(songTitle(S.songs.find(s=>s.id===a.songId)))+'</small><b>'+esc(a.title)+'</b><small>'+esc(a.reason)+'</small></span><span aria-hidden="true">›</span></button>').join(''):'<p class="hint">表示中の曲に確認待ちはありません。</p>')+'<p class="workflow-footnote">表示中の曲の期限・前後の作業・連絡待ちから表示</p></details><button class="production-more workflow-home-button" data-workflow-home>仕事をまとめる</button></section>'}
function wireWorkflow(root){root.querySelectorAll('[data-workflow-home]').forEach(b=>b.onclick=()=>workflowHub());root.querySelectorAll('[data-workflow-priority]').forEach(b=>b.onclick=()=>{const s=S.songs.find(x=>x.id===b.dataset.wfSong);if(!s||RO)return;if(b.dataset.wfType==='communication')workflowContact(s,b.dataset.wfKey);else if(b.dataset.wfType==='issue')workflowIssues(s);else productionTaskEditor(s,b.dataset.wfKey)})}
function refreshWorkflow(){const old=document.getElementById('workflowToday');if(old){const opened=old.querySelector('details')?.open,holder=document.createElement('div');holder.innerHTML=workflowToday(pool());if(holder.querySelector('details'))holder.querySelector('details').open=!!opened;old.replaceWith(holder.firstElementChild);wireWorkflow(document.getElementById('workflowToday'))}const inv=document.getElementById('invoiceOverviewRows');if(inv)invoiceOverviewRefresh(inv)}
function workflowHub(s){
 if(RO)return;const rows=s?[['materials','制作資料','歌録り・先生への送付・ミックス前の不足を確認'],['contacts','連絡と返事待ち','メール・LINEのやり取りと次の担当'],['calendar','空き時間を探す','自分とスタジオの予定から作業枠を確認'],['issues','歌チェックからの申し送り','編集・再録・確認を分けて制作につなげる'],['work','実施した作業','伝票・週報に使う実績を記録'],['invoice','請求書',invoiceReport(s).title],['aliases','略称・仮題','メール・カレンダー・伝票の照合用']]:[['mail','曲の連絡を探す','曲を選んでGmailを確認'],['calendar','空き時間を探す','Googleカレンダーの予定から確認'],['meeting','会議・LINEの内容を整理','複数曲の状況を貼り付けて相談'],['utacheck','歌チェックを取り込む','編集・再録の申し送りを曲ごとに確認'],['reports','伝票・週報・進捗報告','実績と正式タイトルから作成'],['invoice','請求書をまとめて確認','未受領と小森さんへの送付待ち']];
 s3(s?songTitle(s):'進行',s?'連絡・資料':'仕事をまとめる',(s?productionFolderControls(s):'')+wfLinks(rows)+'<div class="workflow-secondary">'+wfRow('connect','接続設定','Gmail・Googleカレンダー・Dropbox')+'</div>',[{t:'閉じる',c:'btn',f:()=>hide('sheet3')}]);
 wireProduction(document.getElementById('s3Body'));
 wfWire({materials:()=>workflowMaterials(s),contacts:()=>workflowContacts(s),calendar:()=>workflowCalendar(s),issues:()=>workflowIssues(s),work:()=>workflowWork(s),aliases:()=>workflowAliases(s),invoice:()=>s?invoiceSheet(s):invoiceOverview(),mail:()=>workflowChooseSong('Gmailを確認',workflowMail),meeting:()=>{cur=null;plannerSheet('以下の連絡・会議メモを曲ごとに整理してください。曲が曖昧なものは確認し、決まったこと・返事待ち・次の作業と日程変更を提案してください。未定を確定にせず、必要なメール／LINEの下書きもお願いします。\n\n')},utacheck:()=>workflowUtacheck(),reports:()=>workflowReports(),connect:()=>workflowConnections(()=>workflowHub(s))});
}
function workflowChooseSong(title,next){s3('曲を選択',title,wfSelect('曲','wfSong',[['','選んでください'],...S.songs.map(s=>[s.id,(s.artist?s.artist+' · ':'')+songTitle(s)])],''),[{t:'戻る',c:'btn',f:()=>workflowHub()},{sp:1},{t:'開く',c:'btn pri',f:()=>{const s=S.songs.find(s=>s.id===wfValue('wfSong'));if(s)next(s);else toast('曲を選んでください')}}])}
function workflowAliases(s){const initial=JSON.stringify(s.workflow||{});s3(songTitle(s),'略称・仮題',wfArea('照合に使う呼び方（1行にひとつ）','wfAliases',(s.workflow?.aliases||[]).join('\n'))+'<p class="hint">同じ略称が複数曲に当てはまる場合は、曲を選んで確認します。</p>',[{t:'戻る',c:'btn',f:()=>workflowHub(s)},{sp:1},{t:'保存',c:'btn pri',f:()=>{if(!wfGuard(s,initial))return;s.workflow||={};s.workflow.aliases=[...new Set(wfValue('wfAliases').split('\n').map(x=>x.trim()).filter(Boolean))].slice(0,20);productionAfterSave(s);workflowHub(s)}}])}
function workflowConnections(back=()=>workflowHub()){
 if(RO)return;wfSetup();const st=WC.status(),c=S.settings.connections||{},origin=location.origin,callback=new URL('oauth-callback.html',location.href).href.split('?')[0];
 const h='<p class="hint">'+(DEMO?'デモでは接続・外部送信を行いません。':'必要なときに接続して読み込みます。接続期限が切れたら再接続できます。')+'</p><div class="workflow-connection"><b>Google</b><small>'+(!c.googleClientId?'接続設定が必要':st.google?'この画面で接続中':'未接続')+'</small><div class="workflow-actions"><button class="btn" id="wfGoogleMail" disabled>Gmailを読む</button><button class="btn" id="wfGoogleCalendar" disabled>予定を読む</button><button class="btn" id="wfGoogleDraft" disabled>下書きを保存</button><button class="btn" id="wfGoogleEvent" disabled>自分の予定を登録</button></div></div><div class="workflow-connection"><b>Dropbox</b><small>'+(!c.dropboxAppKey?'接続設定が必要':st.dropbox?'この画面で接続中':'未接続')+'</small><button class="btn" id="wfDropboxConnect" '+(DEMO||!c.dropboxAppKey?'disabled':'')+'>Dropboxに接続</button></div>'+
 '<p class="hint" id="wfConnectStatus" role="status"></p><details class="production-contact" '+(!c.googleClientId&&!c.dropboxAppKey?'open':'')+'><summary>アプリの接続設定</summary><p class="hint">ChatGPTの接続とは別に、このアプリ用の設定が必要です。クライアントシークレットやAPIキーはここには入れません。</p>'+productionField('Google OAuth クライアントID','wfGoogleId',c.googleClientId||'')+productionField('Dropbox App key','wfDropboxKey',c.dropboxAppKey||'')+'<p class="hint">Googleの承認済みJavaScript生成元：<br>'+esc(origin)+'<br>DropboxのRedirect URI：<br>'+esc(callback)+'</p><p><a href="https://console.cloud.google.com/auth/clients" target="_blank" rel="noopener noreferrer">Googleの設定 ↗</a> · <a href="https://www.dropbox.com/developers/apps" target="_blank" rel="noopener noreferrer">Dropboxの設定 ↗</a></p><p class="hint">GoogleはGmail API／Calendar APIと利用するアカウント、Dropboxはfiles.metadata.read・files.content.read・sharing.readを設定します。</p><button class="btn w" id="wfSaveConnections">接続設定を保存</button></details><button class="production-more" id="wfDisconnect">この画面の接続を解除</button>';
 s3('外部サービス','接続設定',h,[{t:'戻る',c:'btn',f:back}]);const status=document.getElementById('wfConnectStatus');
 const connect=async(button,fn)=>{button.disabled=true;status.textContent='接続画面でアカウントと許可を確認してください。';try{await fn();if(status.isConnected){status.textContent='接続しました。戻って使う機能を選べます。';button.disabled=false}}catch(e){if(status.isConnected){status.textContent=e.message;button.disabled=false}}};
 if(c.googleClientId&&!DEMO)WC.prepareGoogle().then(()=>{if(!status.isConnected)return;for(const [id,kind]of [['Mail','gmail'],['Calendar','calendar'],['Draft','draft'],['Event','event']]){const b=document.getElementById('wfGoogle'+id);b.disabled=false;b.onclick=()=>connect(b,()=>WC.connectGoogle(kind))}}).catch(e=>{if(status.isConnected)status.textContent=e.message});
 document.getElementById('wfDropboxConnect').onclick=e=>connect(e.currentTarget,()=>WC.connectDropbox());
 document.getElementById('wfSaveConnections').onclick=()=>{const googleClientId=wfValue('wfGoogleId').trim(),dropboxAppKey=wfValue('wfDropboxKey').trim();if(googleClientId&&!/^[\w.-]+\.apps\.googleusercontent\.com$/.test(googleClientId))return toast('GoogleのクライアントIDを確認してください');if(dropboxAppKey&&!/^[a-zA-Z0-9_-]{6,100}$/.test(dropboxAppKey))return toast('DropboxのApp keyを確認してください');WC.disconnect();S.settings.connections={...c,googleClientId,dropboxAppKey};mark();workflowConnections(back)};
 document.getElementById('wfDisconnect').onclick=()=>{WC.disconnect();workflowConnections(back)};
}
function workflowMaterials(s,set='recording'){
 if(RO)return;const report=WF.materialReport(s,set),other=WF.list(s,'materials').filter(x=>!x.removed&&!report.some(r=>r.kind===x.kind));
 const row=f=>wfRow('file:'+f.id,f.name,(f.approved?'✓ 内容確認済み':'内容を確認')+(f.rev?' · 版 '+f.rev:'')+(f.previousApproval?' · 更新あり':''));
 let h=wfSelect('準備する用途','wfMaterialSet',Object.entries(WF.sets).map(([k,v])=>[k,v.name]),set)+report.map(r=>'<section class="workflow-section"><h3>'+esc(r.label)+'<small>'+(!r.files.length?'未登録':r.ready?'準備済み':'内容確認待ち')+'</small></h3>'+(r.files.map(row).join('')||'<p class="hint">必要な資料を登録してください。</p>')+'</section>').join('')+(other.length?'<details class="production-omitted"><summary>ほかの資料</summary>'+other.map(row).join('')+'</details>':'')+'<div class="workflow-actions"><button class="btn" id="wfMaterialAdd">資料を登録</button><button class="btn" id="wfMaterialDropbox">Dropboxから選ぶ</button></div><p class="hint">届いたことと、使える内容かの確認は分けて記録します。資料を確認済みにしても制作工程は完了しません。</p>';
 s3(songTitle(s),'制作資料',h,[{t:'戻る',c:'btn',f:()=>workflowHub(s)},{sp:1},{t:'送付の準備',c:'btn pri',f:()=>workflowBundle(s,set)}]);document.getElementById('wfMaterialSet').onchange=e=>workflowMaterials(s,e.target.value);document.getElementById('wfMaterialAdd').onclick=()=>workflowMaterial(s,null,set);document.getElementById('wfMaterialDropbox').onclick=()=>workflowDropbox(s,'',set);
 wfWire(Object.fromEntries(WF.list(s,'materials').map(f=>['file:'+f.id,()=>workflowMaterial(s,f.id,set)])));
}
function workflowMaterial(s,id,set='recording',candidate){const initial=JSON.stringify(s.workflow||{}),old=WF.list(s,'materials').find(x=>x.id===id),f=old||candidate||{id:uid(),kind:WF.sets[set].kinds[0],name:'',url:'',rev:''};
 const h=productionField('資料名','wfMaterialName',f.name)+wfSelect('種類','wfMaterialKind',Object.entries(WF.kindNames),f.kind)+productionField('資料のリンク','wfMaterialURL',f.url||'','url')+(f.source==='dropbox'?'<p class="hint">Dropbox内：'+esc(f.path||f.name)+'<br>取得した版 '+esc(f.rev)+'。共有する場合はファイルのリンクも登録してください。</p>'+productionFolderLink(s):'')+productionField('版・更新日など','wfMaterialRevision',f.rev||'')+'<label class="workflow-check"><input type="checkbox" id="wfMaterialApproved" '+(f.approved?'checked':'')+'>中身を確認し、この用途に使える</label>'+wfArea('補足','wfMaterialMemo',f.memo,3)+(old?'<button class="production-more" id="wfMaterialRemove">この資料を一覧から外す</button>':'');
 s3(songTitle(s),old?'資料を確認':'資料を登録',h,[{t:'戻る',c:'btn',f:()=>workflowMaterials(s,set)},{sp:1},{t:'保存',c:'btn pri',f:()=>{if(!wfGuard(s,initial))return;try{const requested=document.getElementById('wfMaterialApproved').checked,row=WF.saveMaterial(s,{...f,name:wfValue('wfMaterialName'),kind:wfValue('wfMaterialKind'),url:wfValue('wfMaterialURL'),rev:wfValue('wfMaterialRevision'),memo:wfValue('wfMaterialMemo'),removed:false,approved:requested,approvedAt:requested?new Date().toISOString():''});productionAfterSave(s);workflowMaterials(s,set);if(requested&&!row.approved)toast('版やリンクを変更したので、内容をもう一度確認してください')}catch(e){toast(e.message)}}}]);
 const remove=document.getElementById('wfMaterialRemove');if(remove)remove.onclick=()=>{if(!wfGuard(s,initial))return;WF.upsert(s,'materials',{...f,removed:true});productionAfterSave(s);workflowMaterials(s,set)};
}
async function workflowDropbox(s,path='',set='recording'){
 if(RO)return;if(!s.dropboxUrl){productionFolderSheet(s);return}wfSetup();if(!WC.status().dropbox||DEMO){workflowConnections(()=>workflowMaterials(s,set));return}
 s3(songTitle(s),'Dropboxから資料を選ぶ','<p class="hint" id="wfDropboxStatus" role="status">このフォルダを確認しています…</p>',[{t:'戻る',c:'btn',f:()=>workflowMaterials(s,set)}]);const el=document.getElementById('wfDropboxStatus'),url=s.dropboxUrl;
 try{const files=await WC.dropboxList(url,path);if(!el.isConnected||!S.songs.includes(s)||s.dropboxUrl!==url)return;const holder=el.parentElement;holder.innerHTML='<p class="hint">'+esc(path||'曲のフォルダ')+' · '+files.length+'件。ファイルを選んで用途と中身を確認します。</p>'+(path?wfRow('up','上のフォルダへ'):'')+files.map((f,i)=>wfRow('file'+i,f.name,f['.tag']==='folder'?'フォルダ':(f.server_modified||'').slice(0,10))).join('')+(!files.length?'<p class="hint">ファイルがありません。</p>':'');const actions={up:()=>workflowDropbox(s,path.split('/').slice(0,-1).join('/'),set)};
 files.forEach((f,i)=>actions['file'+i]=()=>{const child=path+'/'+f.name;if(f['.tag']==='folder')return workflowDropbox(s,child,set);const id='dropbox:'+f.id,old=WF.list(s,'materials').find(x=>x.id===id);workflowMaterial(s,null,set,{...old,id,name:f.name,kind:old?.kind||WF.materialKind(f.name),source:'dropbox',path:child,rev:f.rev,url:old?.url||'',approved:false,sourceFolder:url,previousApproval:old?.approved&&old.rev!==f.rev?{name:old.name,rev:old.rev}:old?.previousApproval})});wfWire(actions);
 }catch(e){if(el.isConnected){el.textContent=e.message;const b=document.createElement('button');b.className='btn';b.textContent='接続設定';b.onclick=()=>workflowConnections(()=>workflowMaterials(s,set));el.after(b)}}
}
function workflowBundle(s,set){const bundle=WF.materialBundle(s,set),initial=JSON.stringify(s.workflow||{}),names=bundle.files.map(f=>f.name).join('、');
 const body='お世話になっております。\n\n'+(s.artist||'')+'「'+songTitle(s)+'」の'+WF.sets[set].name+'の資料をお送りします。\n\n'+bundle.text+'\n\nご確認をお願いいたします。';
 workflowDraft(s,{subject:songTitle(s)+'／'+WF.sets[set].name+'の資料',body},()=>workflowMaterials(s,set),()=>{if(!wfGuard(s,initial))return false;WF.upsert(s,'deliveries',{id:uid(),set,at:new Date().toISOString(),files:bundle.files.map(f=>({id:f.id,name:f.name,rev:f.rev||'',url:f.url||''}))});productionAfterSave(s);return true},{notice:bundle.missing.length?'不足：'+bundle.missing.join('、')+'。不足分を確認してから送付してください。':'送付する資料：'+(names||'未選択'),allowSent:!bundle.missing.length&&bundle.files.length>0});
}
function workflowContacts(s){const items=WF.list(s,'communications'),labels={review:'内容確認',reply:'自分の返信待ち',waiting:'相手の返事待ち',done:'対応済み'};s3(songTitle(s),'連絡と返事待ち',wfLinks(items.filter(c=>c.state!=='done').map(c=>[c.id,c.subject||c.person,labels[c.state]+(c.person?' · '+c.person:'')+(c.due?' · '+c.due:'')]))+(!items.length?'<p class="hint">メール・LINEで依頼したことや、返事待ちをまとめられます。</p>':'')+(items.some(c=>c.state==='done')?'<details class="production-omitted"><summary>対応済みを見る</summary>'+wfLinks(items.filter(c=>c.state==='done').map(c=>[c.id,c.subject||c.person,'対応済み']))+'</details>':'')+'<div class="workflow-actions"><button class="btn" id="wfContactAdd">連絡を記録</button><button class="btn" id="wfMailSearch">Gmailから探す</button></div>',[{t:'戻る',c:'btn',f:()=>workflowHub(s)}]);wfWire(Object.fromEntries(items.map(c=>[c.id,()=>workflowContact(s,c.id)])));document.getElementById('wfContactAdd').onclick=()=>workflowContact(s);document.getElementById('wfMailSearch').onclick=()=>workflowMail(s)}
function workflowContact(s,id,candidate){if(RO)return;const initial=JSON.stringify(s.workflow||{}),prior=WF.list(s,'communications').find(x=>x.id===id),c=(candidate?{...prior,...candidate}:prior)||{id:uid(),state:'review',channel:'email'};const tasks=productionReport(s).nodes;
 const h=productionField('用件','wfContactSubject',c.subject)+productionField('相手の名前','wfContactPerson',c.person)+productionField('メールアドレス','wfContactEmail',c.email||'','email')+wfSelect('連絡手段','wfContactChannel',[['email','メール'],['line','LINE'],['meeting','会議・口頭']],c.channel)+wfSelect('次に動くのは','wfContactState',[['review','内容を確認して決める'],['reply','自分（返信・対応する）'],['waiting','相手（返事を待つ）'],['done','この連絡の対応は完了']],c.state)+productionField('いつ確認するか','wfContactDue',c.due||'','date')+wfSelect('関連する作業','wfContactTask',[['','未設定'],...tasks.map(n=>[n.id,n.label])],c.taskId||'')+wfArea('内容・伝えること','wfContactMemo',c.memo||'')+(c.url?'<a class="production-more" href="'+esc(c.url)+'" target="_blank" rel="noopener noreferrer">元の連絡を開く ↗</a>':'')+'<p class="hint">連絡を対応済みにしても、制作作業の完了にはしません。</p><button class="btn w" id="wfContactDraft">保存して連絡文を作る</button>';
 const save=()=>{if(!wfGuard(s,initial))return;try{const row=WF.saveCommunication(s,{...c,subject:wfValue('wfContactSubject'),person:wfValue('wfContactPerson'),email:wfValue('wfContactEmail'),channel:wfValue('wfContactChannel'),state:wfValue('wfContactState'),due:wfValue('wfContactDue'),taskId:wfValue('wfContactTask'),memo:wfValue('wfContactMemo')});productionAfterSave(s);return row}catch(e){toast(e.message)}};
 s3(songTitle(s),'連絡を記録',h,[{t:'戻る',c:'btn',f:()=>workflowContacts(s)},{sp:1},{t:'保存',c:'btn pri',f:()=>{if(save())workflowContacts(s)}}]);document.getElementById('wfContactDraft').onclick=()=>{const row=save();if(!row)return;const snapshot=JSON.stringify(s.workflow||{});workflowDraft(s,WF.communicationDraft(s,row),()=>workflowContact(s,row.id),()=>{if(!wfGuard(s,snapshot))return false;WF.saveCommunication(s,{...row,state:'waiting',updatedAt:Date.now()});productionAfterSave(s);return true},{channel:row.channel})};
}
async function workflowMail(s){
 if(RO)return;wfSetup();if(!WC.status().google||!WC.status().scopes.includes(WC.SCOPES.gmail)||DEMO){workflowConnections(()=>workflowContacts(s));return}
 s3(songTitle(s),'Gmailで曲の連絡を確認','<p class="hint" id="wfMailStatus" role="status">過去180日のメールを曲名・略称で確認しています…</p>',[{t:'戻る',c:'btn',f:()=>workflowContacts(s)}]);const el=document.getElementById('wfMailStatus');
 try{const result=await WC.mailSearch(s);if(!el.isConnected||!S.songs.includes(s))return;el.parentElement.innerHTML='<p class="hint">最新'+result.messages.length+'通'+(result.more?'（続きはGmailで確認できます）':'')+'。曲が合っているか確認してから記録します。</p>'+wfLinks(result.messages.map((m,i)=>['m'+i,WC.head(m,'Subject'),WC.head(m,'From')+' · '+new Date(Number(m.internalDate)).toLocaleDateString('ja-JP')]))+(!result.messages.length?'<p class="hint">一致するメールがありません。曲の略称を登録すると探しやすくなります。</p>':'');wfWire(Object.fromEntries(result.messages.map((m,i)=>['m'+i,()=>workflowMailMessage(s,m)])))}catch(e){if(el.isConnected)el.textContent=e.message}
}
async function workflowMailMessage(s,m){
 s3(songTitle(s),'連絡内容の確認','<p class="hint" id="wfMailRead" role="status">やり取りを読み込んでいます…</p>',[{t:'戻る',c:'btn',f:()=>workflowMail(s)}]);const el=document.getElementById('wfMailRead');
 try{const thread=await WC.mailThread(m.threadId);if(!el.isConnected||!S.songs.includes(s))return;const messages=(thread.messages||[]).sort((a,b)=>Number(a.internalDate)-Number(b.internalDate)),last=messages.at(-1);if(!last)throw Error('本文がありません');const sent=(last.labelIds||[]).includes('SENT'),party=WC.head(last,sent?'To':'From'),email=party.match(/[^\s<>;,]+@[^\s<>;,]+\.[^\s<>;,]+/)?.[0]||'',text=WC.mailText(last.payload)||last.snippet||'',url='https://mail.google.com/mail/u/0/#all/'+m.threadId;
 const attached=WC.attachments(last.payload);
 s3(songTitle(s),'曲と対応を確認','<p class="workflow-mail-meta">'+esc(WC.head(last,'Subject'))+'<br>'+esc(party)+'</p><pre class="workflow-message">'+esc(text)+'</pre>'+(attached.length?'<p class="hint">添付：'+attached.map(f=>esc(f.name)).join('、')+'</p><a class="production-more" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">Gmailで添付を確認 ↗</a><button class="btn w" id="wfMailInvoice">確認した請求書の受領を記録</button>':'')+'<p class="hint">このやり取りは「'+esc(songTitle(s))+'」ですか？ 受信しただけでは完了にしません。</p>',[{t:'戻る',c:'btn',f:()=>workflowMail(s)},{sp:1},{t:'この曲の連絡に記録',c:'btn pri',f:()=>workflowContact(s,'gmail:'+m.threadId,{id:'gmail:'+m.threadId,subject:WC.head(last,'Subject'),person:party.replace(/<.*>/,'').trim(),email,channel:'email',state:'review',memo:text.slice(0,4000),sourceId:m.threadId,sourceModified:last.id,url})}]);
 const inv=document.getElementById('wfMailInvoice');if(inv)inv.onclick=()=>workflowInvoiceReceipt(s,{url,subject:WC.head(last,'Subject'),from:party,attachments:attached,sourceId:last.id});
 }catch(e){if(el.isConnected)el.textContent=e.message}
}
function workflowDraft(s,draft,back,onSent,options={}){
 if(RO)return;const h=(options.notice?'<p class="workflow-notice">'+esc(options.notice)+'</p>':'')+productionField('宛先メールアドレス','wfDraftTo',draft.to||'','email')+productionField('件名','wfDraftSubject',draft.subject||'')+'<button class="production-more" id="wfCopySubject">件名をコピー</button>'+wfArea('本文','wfDraftBody',draft.body||'',10)+'<button class="production-more" id="wfCopyBody">本文をコピー</button><div class="workflow-actions"><button class="btn" id="wfOpenMail">メールを開く</button><button class="btn" id="wfGmailDraft">Gmailに下書き保存</button></div><p class="hint">LINEは本文をコピーして送れます。Gmailの下書きは送信されません。</p><p class="hint" id="wfDraftStatus" role="status"></p>';
 s3(s?songTitle(s):'制作全体','連絡文の下書き',h,[{t:'戻る',c:'btn',f:back},...(onSent&&options.allowSent!==false?[{sp:1},{t:'送信したことを記録',c:'btn pri',f:()=>{if(onSent()){toast('送付を記録しました');back()}}}]:[])]);
 const status=document.getElementById('wfDraftStatus'),read=()=>({to:wfValue('wfDraftTo').trim(),subject:wfValue('wfDraftSubject'),body:wfValue('wfDraftBody')});for(const [id,input]of [['wfCopySubject','wfDraftSubject'],['wfCopyBody','wfDraftBody']])document.getElementById(id).onclick=()=>invoiceCopy(input,'wfDraftStatus');
 document.getElementById('wfOpenMail').onclick=()=>{const d=read();if(!WF.validEmail(d.to))return toast('宛先を確認してください');location.href='mailto:'+encodeURIComponent(d.to)+'?subject='+encodeURIComponent(d.subject)+'&body='+encodeURIComponent(d.body)};
 document.getElementById('wfGmailDraft').onclick=async e=>{wfSetup();const d=read();if(!WF.validEmail(d.to))return toast('宛先を確認してください');if(!WC.status().scopes.includes(WC.SCOPES.draft)||DEMO){workflowConnections(()=>workflowDraft(s,d,back,onSent,options));return}const b=e.currentTarget;b.disabled=true;status.textContent='Gmailに下書きを保存しています…';try{await WC.createDraft(d);if(status.isConnected)status.textContent='Gmailの下書きに保存しました。宛先・本文・添付を確認して送信してください。'}catch(e){if(status.isConnected){status.textContent=e.message+'。重複を避けるため、Gmailの下書きも確認してください。';b.disabled=false}}};
 if(s)productionInsertFolderButton(s,'wfDraftBody','s3Body');
}
function workflowCalendar(s,saved){
 if(RO)return;wfSetup();const cfg=S.settings.connections||{},calendars=cfg.calendars||[],selected=saved?.selected||cfg.selectedCalendars||[];
 const h=productionField('日付','wfCalendarDay',saved?.day||D.today(),'date')+wfSelect('作業時間','wfCalendarDuration',[['60','1時間'],['120','2時間'],['180','3時間'],['240','4時間'],['360','6時間'] ],saved?.duration||'180')+productionField('予定の名前','wfCalendarTitle',saved?.title||((s?songTitle(s)+'／':'')+'作業'))+'<section class="workflow-section"><h3>空きを確認するカレンダー</h3>'+(calendars.map(c=>'<label class="workflow-check"><input type="checkbox" data-calendar-id="'+esc(c.id)+'" '+(selected.includes(c.id)?'checked':'')+'>'+esc(c.summary)+'</label>').join('')||'<p class="hint">Googleに接続して、予定を確認するカレンダーを選んでください。</p>')+'</section>'+wfSelect('登録するカレンダー','wfCalendarTarget',[['','選んでください'],...calendars.filter(c=>['owner','writer'].includes(c.accessRole)).map(c=>[c.id,c.summary])],saved?.target||cfg.eventCalendar||'')+'<div class="workflow-actions"><button class="btn" id="wfCalendarsRead">カレンダーを読み込む</button><button class="btn" id="wfCalendarFind">空き時間を確認</button></div><p class="hint">日本時間の10〜21時から確認します。候補を押して内容を確認するまで、予定は登録しません。</p><p class="hint" id="wfCalendarStatus" role="status"></p><div id="wfCalendarSlots"></div>';
 s3(s?songTitle(s):'制作全体','作業時間を確保',h,[{t:'戻る',c:'btn',f:()=>workflowHub(s)}]);const status=document.getElementById('wfCalendarStatus'),slots=document.getElementById('wfCalendarSlots'),read=()=>({day:wfValue('wfCalendarDay'),duration:wfValue('wfCalendarDuration'),title:wfValue('wfCalendarTitle'),target:wfValue('wfCalendarTarget'),selected:[...document.querySelectorAll('[data-calendar-id]:checked')].map(x=>x.dataset.calendarId)});
 const connected=()=>WC.status().scopes.includes(WC.SCOPES.calendar)&&WC.status().google&&!DEMO;
 document.getElementById('wfCalendarsRead').onclick=async e=>{const data=read();if(!connected()){workflowConnections(()=>workflowCalendar(s,data));return}const b=e.currentTarget;b.disabled=true;status.textContent='カレンダーを確認しています…';try{const cs=await WC.calendars();if(!status.isConnected)return;S.settings.connections={...cfg,calendars:cs.map(({id,summary,accessRole,primary})=>({id,summary,accessRole,primary}))};mark();workflowCalendar(s,{...data,selected:data.selected.length?data.selected:cs.filter(c=>c.primary).map(c=>c.id)})}catch(e){if(status.isConnected){status.textContent=e.message;b.disabled=false}}};
 document.getElementById('wfCalendarFind').onclick=async e=>{const data=read();if(!connected()){workflowConnections(()=>workflowCalendar(s,data));return}if(!ShinkouProduction.validDate(data.day)||!data.selected.length)return toast('日付とカレンダーを選んでください');const b=e.currentTarget;b.disabled=true;slots.innerHTML='';status.textContent='選択した予定をすべて確認しています…';try{const events=await WC.busy(data.selected,data.day);if(!status.isConnected)return;const found=WF.freeSlots(events,data.day,Number(data.duration));S.settings.connections={...S.settings.connections,selectedCalendars:data.selected,eventCalendar:data.target};mark();status.textContent=found.length?'空いている候補です。相手やスタジオの確定予約は別途確認してください。':'この条件でまとまった空きが見つかりませんでした。';slots.innerHTML=found.map((slot,i)=>wfRow('slot'+i,wfTime(slot.start)+'〜'+wfTime(slot.end),'この時間で予定を確認')).join('');wfWire(Object.fromEntries(found.map((slot,i)=>['slot'+i,()=>workflowCalendarConfirm(s,data,slot)])))}catch(e){if(status.isConnected)status.textContent=e.message}finally{if(b.isConnected)b.disabled=false}};
}
function wfTime(value){return new Date(value).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'})}
function workflowCalendarConfirm(s,data,slot){const calendar=S.settings.connections?.calendars?.find(c=>c.id===data.target),id=crypto.randomUUID().replaceAll('-','');
 s3(s?songTitle(s):'制作全体','予定の確認','<div class="workflow-notice"><b>'+esc(data.title)+'</b><p>'+esc(data.day)+' '+wfTime(slot.start)+'〜'+wfTime(slot.end)+'（日本時間）</p><p>'+esc(calendar?.summary||'登録先が未選択です')+'</p></div><p class="hint">自分のカレンダーに予定を入れます。参加者への招待・連絡や、曲の工程の完了処理は行いません。</p><p class="hint" id="wfEventStatus" role="status"></p>',[{t:'戻る',c:'btn',f:()=>workflowCalendar(s,data)},{sp:1},{t:'この予定を登録',c:'btn pri',f:async()=>{
  const status=document.getElementById('wfEventStatus'),b=document.querySelector('#s3Foot .pri');if(RO||DEMO)return toast('デモ・閲覧画面では登録しません');if(s&&!S.songs.includes(s))return toast('曲が更新されています');if(!calendar||!['owner','writer'].includes(calendar.accessRole))return toast('登録先を選んでください');if(!data.title.trim())return toast('予定の名前を入力してください');
  if(!WC.status().scopes.includes(WC.SCOPES.event)){workflowConnections(()=>workflowCalendarConfirm(s,data,slot));return}b.disabled=true;status.textContent='登録前に、空き時間を再確認しています…';
  try{const events=await WC.busy([...new Set([...data.selected,data.target])],data.day);if(!status.isConnected)return;const start=Date.parse(slot.start),end=Date.parse(slot.end);if(events.some(e=>Date.parse(e.start.dateTime)<end&&Date.parse(e.end.dateTime)>start))throw Error('この時間に予定が入りました。空き候補を選び直してください');status.textContent='予定を登録しています…';const event=await WC.createEvent(data.target,{id,summary:data.title,start:{dateTime:slot.start},end:{dateTime:slot.end},description:s?'進行の曲ID: '+s.id+'\n'+(s.artist||'')+' '+songTitle(s):'進行で確保した作業時間',extendedProperties:{private:{shinkouSongId:s?.id||'',shinkouOperation:id}}});if(s&&S.songs.includes(s)){WF.upsert(s,'calendarEvents',{id:event.id,calendarId:data.target,start:slot.start,end:slot.end,title:data.title,url:WF.safeURL(event.htmlLink),at:Date.now()});productionAfterSave(s)}if(status.isConnected)status.textContent='登録しました。相手への依頼が必要なら、曲の「連絡と返事待ち」から文面を作れます。';
  }catch(e){if(status.isConnected)status.textContent=e.message+'。登録結果が不明な場合は、Googleカレンダーを確認してください。'}
 }}]);
}
function workflowWork(s,id){const rows=WF.list(s,'workLogs').filter(w=>!w.removed).sort((a,b)=>b.date.localeCompare(a.date)),initial=JSON.stringify(s.workflow||{}),old=rows.find(w=>w.id===id),w=old||{id:uid(),kind:'edit',date:D.today(),start:'',end:'',confirmed:false};
 const h=wfSelect('実際に行った作業','wfWorkKind',Object.entries(WF.workKinds),w.kind)+productionField('実施日','wfWorkDate',w.date,'date')+'<div class="workflow-two">'+productionField('開始','wfWorkStart',w.start,'time')+productionField('終了','wfWorkEnd',w.end,'time')+'</div>'+productionField('担当者','wfWorkPerson',w.person||'')+wfArea('内容','wfWorkMemo',w.memo||'',3)+'<label class="workflow-check"><input type="checkbox" id="wfWorkConfirmed" '+(w.confirmed?'checked':'')+'>実際に行った作業・時間として確認済み</label><p class="hint">予定だけの記録は伝票・週報に含めません。日をまたぐ作業は日ごとに分けて記録します。</p>'+(old?'<button class="production-more" id="wfWorkRemove">この実績を一覧から外す</button>':'')+(rows.length?'<details class="production-omitted"><summary>これまでの実績</summary>'+wfLinks(rows.map(x=>[x.id,x.date+' '+WF.workKinds[x.kind],x.start+'〜'+x.end+(x.confirmed?' · 確認済み':' · 未確認')])).concat('</details>'):'')+'<button class="production-more" id="wfWorkReports">伝票・週報へ出力</button>';
 s3(songTitle(s),old?'実績を編集':'実施した作業を記録',h,[{t:'戻る',c:'btn',f:()=>workflowHub(s)},{sp:1},{t:'保存',c:'btn pri',f:()=>{if(!wfGuard(s,initial))return;try{WF.saveWork(s,{...w,kind:wfValue('wfWorkKind'),date:wfValue('wfWorkDate'),start:wfValue('wfWorkStart'),end:wfValue('wfWorkEnd'),person:wfValue('wfWorkPerson'),memo:wfValue('wfWorkMemo'),confirmed:document.getElementById('wfWorkConfirmed').checked});productionAfterSave(s);workflowWork(s);toast('実績を保存しました')}catch(e){toast(e.message)}}}]);wfWire(Object.fromEntries(rows.map(x=>[x.id,()=>workflowWork(s,x.id)])));document.getElementById('wfWorkReports').onclick=()=>workflowReports(s);const remove=document.getElementById('wfWorkRemove');if(remove)remove.onclick=()=>{if(!wfGuard(s,initial))return;WF.upsert(s,'workLogs',{...w,removed:true});productionAfterSave(s);workflowWork(s)};
}
function workflowReports(s){const today=D.today(),from=new Date(Date.parse(today)-6*864e5).toISOString().slice(0,10),songs=s?[s]:S.songs;
 s3(s?songTitle(s):'制作全体','伝票・週報・進捗報告','<div class="workflow-two">'+productionField('開始日','wfReportFrom',from,'date')+productionField('終了日','wfReportTo',today,'date')+'</div>'+wfLinks([['voucher','エンジニア伝票用CSV','実施確認済みの録音・編集・ミックスと正式タイトル'],['weekly','週報の下書き','実施確認済みの作業を日付順にまとめる'],['progress','進捗報告の下書き','どこまで済んだかと主要日程だけを共有'],['catalog','曲情報をほかのプロジェクトへ','曲ID・正式タイトル・アーティスト・略称のJSON']])+'<p class="hint">CSV／JSONを伝票作成側のChatGPTプロジェクトに渡せます。曲IDで照合し、略称から正式タイトルを参照できます。</p>',[{t:'戻る',c:'btn',f:()=>workflowHub(s)}]);
 const range=()=>{const a=wfValue('wfReportFrom'),b=wfValue('wfReportTo');if(!ShinkouProduction.validDate(a)||!ShinkouProduction.validDate(b)||b<a){toast('期間を確認してください');return}return [a,b]};wfWire({voucher:()=>{const r=range();if(r)dlFile('shinkou-engineer-'+r[0]+'-'+r[1]+'.csv',WF.csv(songs,...r),'text/csv;charset=utf-8')},weekly:()=>{const r=range();if(r)workflowDraft(s,{subject:'週報 '+r[0]+'〜'+r[1],body:WF.weekly(songs,...r)},()=>workflowReports(s))},progress:()=>workflowDraft(s,{subject:'制作進捗 '+today,body:WF.progress(songs,productionReport)},()=>workflowReports(s)),catalog:()=>dlFile('shinkou-song-catalog.json',JSON.stringify(WF.catalog(songs),null,2),'application/json')});
}
function workflowIssues(s){const items=WF.list(s,'issues'),labels={check:'確認が必要',edit:'編集で対応',rerecord:'再録を相談'};
 s3(songTitle(s),'歌チェックの申し送り',wfLinks(items.filter(i=>!i.resolved).map(i=>[i.id,i.members.join('・')||i.tags.join('・')||'確認事項',labels[i.action]+' · '+(i.memo||i.tags.join('・'))]))+(!items.length?'<p class="hint">歌チェックの記録から、編集や再録が必要な箇所を取り込めます。</p>':'')+(items.some(i=>i.resolved)?'<details class="production-omitted"><summary>対応済みを見る</summary>'+wfLinks(items.filter(i=>i.resolved).map(i=>[i.id,i.members.join('・')||'確認事項','対応済み · '+i.memo]))+'</details>':'')+'<button class="btn w" id="wfIssueImport">歌チェックから取り込む</button>',[{t:'戻る',c:'btn',f:()=>workflowHub(s)}]);document.getElementById('wfIssueImport').onclick=()=>workflowUtacheck(s);wfWire(Object.fromEntries(items.map(i=>[i.id,()=>workflowIssue(s,i.id)])));
}
function workflowIssue(s,id){const i=WF.list(s,'issues').find(x=>x.id===id);if(!i)return;const initial=JSON.stringify(s.workflow||{});
 s3(songTitle(s),'歌の対応を決める','<p>'+esc(i.members.join('・'))+'</p><p class="hint">'+esc(i.tags.join('・'))+(Number.isInteger(i.lineIdx)?' · 歌詞 '+(i.lineIdx+1)+'行目':'')+'</p><pre class="workflow-message">'+esc(i.memo||'メモなし')+'</pre>'+wfSelect('対応','wfIssueAction',[['check','確認が必要'],['edit','編集で対応'],['rerecord','再録を相談']],i.action)+'<label class="workflow-check"><input type="checkbox" id="wfIssueResolved" '+(i.resolved?'checked':'')+'>この指摘への対応が済んだ</label><button class="btn w" id="wfIssueConsult">この内容から段取りを相談</button>',[{t:'戻る',c:'btn',f:()=>workflowIssues(s)},{sp:1},{t:'保存',c:'btn pri',f:()=>{if(!wfGuard(s,initial))return;WF.upsert(s,'issues',{...i,action:wfValue('wfIssueAction'),resolved:document.getElementById('wfIssueResolved').checked});productionAfterSave(s);workflowIssues(s)}}]);document.getElementById('wfIssueConsult').onclick=()=>{cur=s;plannerSheet('歌チェックからの申し送りです。\n'+i.members.join('・')+'／'+i.tags.join('・')+'\n'+i.memo+'\n対応案：'+wfValue('wfIssueAction')+'\n必要な編集・再録の日程と連絡文を提案してください。未確定のことは質問してください。')};
}
async function wfUtacheckLocal(){
 if(indexedDB.databases){const dbs=await indexedDB.databases();if(!dbs.some(d=>d.name==='utacheck'))throw Error('このブラウザーに歌チェックの記録がありません。バックアップファイルを選んでください')}
 return new Promise((resolve,reject)=>{const req=indexedDB.open('utacheck');req.onupgradeneeded=()=>{req.transaction.abort();reject(Error('このブラウザーに歌チェックの記録がありません'))};req.onerror=()=>reject(Error('歌チェックの記録を読めませんでした'));req.onsuccess=()=>{const db=req.result;if(!db.objectStoreNames.contains('state')){db.close();reject(Error('歌チェックの記録がありません'));return}const tx=db.transaction('state','readonly'),store=tx.objectStore('state'),rows=[];for(const key of ['state:0','state:1']){const r=store.get(key);r.onsuccess=()=>{if(r.result?.txt)rows.push(r.result)}}tx.oncomplete=()=>{db.close();for(const row of rows.sort((a,b)=>(b.seq||0)-(a.seq||0)))try{return resolve(WF.utacheck(JSON.parse(row.txt)))}catch{}reject(Error('有効な歌チェックの記録がありません'))};tx.onerror=()=>{db.close();reject(Error('歌チェックの記録を読めませんでした'))}}});
}
async function wfUtacheckFile(file,pass){if(file.size>20*1024*1024)throw Error('ファイルが大きすぎます。20MB以下の記録ファイルを選んでください');let data=JSON.parse(await file.text());const decode=s=>Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),x=>x.charCodeAt(0));
 if(data.enc){if(!pass)throw Error('歌チェックのバックアップの合言葉を入力してください');try{const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:decode(data.salt),iterations:200000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']);data=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(data.iv)},key,decode(data.data))))}catch{throw Error('合言葉が合わないか、バックアップが壊れています')}}
 if(data.bk){let bytes=decode(data.data);if(data.z){const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader(),parts=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>30*1024*1024){await reader.cancel();throw Error('展開した記録が大きすぎます')}parts.push(value)}bytes=new Uint8Array(await new Blob(parts).arrayBuffer())}data=JSON.parse(new TextDecoder().decode(bytes))}return WF.utacheck(data);
}
function workflowUtacheck(target){if(RO)return;s3('歌チェック','申し送りを取り込む','<p class="hint">指摘だけを読み取り、曲を選んで取り込みます。歌チェックの音源・キー・元の記録は変更しません。</p><button class="btn w" id="wfUtaLocal">このブラウザーの歌チェックから読む</button><p class="hint">同じブラウザー・同じ公開先で使っている場合に利用できます。</p><label class="quick-field">またはバックアップJSON<input class="inp" id="wfUtaFile" type="file" accept=".json,application/json"></label>'+productionField('合言葉（暗号化されている場合のみ）','wfUtaPass','','password')+'<button class="btn w" id="wfUtaRead">ファイルを読む</button><p class="hint" id="wfUtaStatus" role="status"></p>',[{t:'戻る',c:'btn',f:()=>workflowHub(target)}]);const status=document.getElementById('wfUtaStatus');const read=async fn=>{status.textContent='読み込んでいます…';try{const data=await fn();if(status.isConnected)workflowUtacheckMap(data,target)}catch(e){if(status.isConnected)status.textContent=e.message}};document.getElementById('wfUtaLocal').onclick=()=>DEMO?toast('デモでは実際の歌チェックを読みません'):read(wfUtacheckLocal);document.getElementById('wfUtaRead').onclick=()=>{const f=document.getElementById('wfUtaFile').files[0],pass=wfValue('wfUtaPass');if(f)read(()=>wfUtacheckFile(f,pass));else toast('ファイルを選んでください')};}
function workflowUtacheckMap(sources,target){const rows=sources.map((source,i)=>{const existing=S.songs.find(s=>s.workflow?.utacheckSongId===source.id),match=WF.match(S.songs,source);return {source,i,id:target?.id||existing?.id||match.songId}});
 s3('歌チェック','曲を確認して取り込む',(rows.length?rows.map(({source,i,id})=>'<section class="workflow-section"><h3>'+esc(source.title||'曲名未登録')+'</h3><p class="hint">'+esc(source.artist)+' · '+source.notes.length+'件の指摘</p>'+wfSelect('進行の曲','wfUtaSong'+i,[['','取り込まない'],...S.songs.filter(s=>!target||s.id===target.id).map(s=>[s.id,(s.artist?s.artist+' · ':'')+songTitle(s)])],target&&rows.length>1?'':id)+'</section>').join(''):'<p class="hint">申し送りの指摘がありません。</p>')+'<p class="hint">候補の曲名を確認してください。既に取り込んだ指摘は重複させず、元の内容が変わった指摘は再確認に戻します。</p>',[{t:'戻る',c:'btn',f:()=>workflowUtacheck(target)},{sp:1},{t:'選んだ曲へ取り込む',c:'btn pri',f:()=>{if(RO)return;let count=0;for(const {source,i}of rows){const s=S.songs.find(x=>x.id===wfValue('wfUtaSong'+i));if(s){WF.importIssues(s,source);productionAfterSave(s);count++}}if(!count)return toast('取り込む曲を選んでください');toast(count+'曲の指摘を取り込みました');target?workflowIssues(target):workflowHub()}}]);
}
function workflowImpact(s,id,day,container){const changes=WF.impact(s,id,day,productionReport);container.innerHTML=changes.length?'<p class="hint">日程変更後に確認する作業</p>'+changes.slice(0,8).map(n=>'<p class="workflow-impact '+(n.risk?'risk':'')+'">'+esc(n.label)+(n.date?' · '+esc(n.date):' · 日程未定')+'<small>'+esc(n.reason)+'</small></p>').join('')+'<p class="hint">ほかの日程は自動で変更しません。保存後、必要な連絡を相談できます。</p>':'';}

function workflowInvoiceReceipt(s,mail){const before=ShinkouProduction.invoices.snapshot(s),r=invoiceReport(s),candidates=r.items.filter(x=>!x.received&&x.required!==false);
 s3(songTitle(s),'請求書の受領を確認','<p class="hint">'+esc(mail.from)+'<br>'+esc(mail.subject)+'<br>'+mail.attachments.map(f=>esc(f.name)).join('、')+'</p>'+wfSelect('誰の請求書か','wfInvoiceSender',[['','請求先を選んでください'],...candidates.map(x=>[x.id,x.name+'（'+x.roles.join('・')+'）'])],'')+'<label class="workflow-check"><input type="checkbox" id="wfInvoiceChecked">添付の中身・請求先・対象曲を確認した</label><p class="hint">メールが届いただけでは受領済みや送付済みにしません。請求先がなければ、曲の請求書画面で追加できます。</p>',[{t:'戻る',c:'btn',f:()=>workflowContacts(s)},{sp:1},{t:'受領済みにする',c:'btn pri',f:()=>{const id=wfValue('wfInvoiceSender');if(!id||!document.getElementById('wfInvoiceChecked').checked)return toast('請求先と添付内容を確認してください');invoiceChange(s,{id,action:'received'},before,()=>{WF.upsert(s,'invoiceSources',{id,sourceId:mail.sourceId,url:mail.url,subject:mail.subject,attachments:mail.attachments.map(f=>f.name),at:Date.now()});productionAfterSave(s);invoiceSheet(s)})}}]);
}
