'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const P=require('../production.js'),C=require('../core.js'),W=require('../workflow.js'),today='2026-09-24';
function item(id,artist,done=false){return {id,title:'メドレー',artist,projectId:id,use:'live',dates:{},credits:[],stageList:[{k:'make',n:'作成',gp:'制作'},{k:'mix',n:'ミックス',gp:'制作'},{k:'deliver',n:'納品',gp:'制作'}],stages:{make:{done,date:done?'2026-09-01':'',slots:[]},mix:{done,slots:[]},deliver:{done,slots:[]}}};}
function fixture(){const old=item('old','完了グループ',true),current=item('current','進行中グループ');current.stages.make={done:false,st:'req',asg:'担当者',dl:today,slots:[]};const songs=[old,current],projects=songs.map(s=>({id:s.id,artist:s.artist,custom:s.artist+' 秋公演',mode:'live'}));return {songs,projects};}
const select=(f,text,scope='global')=>P.consultationTargets(f.songs,f.projects,text,scope,today);
test('same title selects only current production and preserves source indices',()=>{const f=fixture(),before=JSON.stringify(f),r=select(f,'メドレーは担当者さん待ちです。今日中に来る予定です。');assert.deepEqual(r.indices,[1]);assert.equal(r.selected,1);assert.equal(JSON.stringify(f),before);assert.deepEqual(select(f,'メドレーが終わりました').indices,[1]);});
test('completed steps are removed from same-title candidates even when other work remains',()=>{const f=fixture();f.songs[0].stages.deliver.done=false;assert.deepEqual(select(f,'メドレーのミックスは今日中です').indices,[1]);});
test('outstanding invoices do not make finished audio a production candidate',()=>{const f=fixture();f.songs[0].credits=[{id:'player',name:'演奏者',parts:['Guitar']}];f.songs[0].invoiceTracking=true;assert.equal(P.report(f.songs[0],{today}).archive,false);assert.deepEqual(select(f,'メドレーは今日中に来る予定です').indices,[1]);assert.deepEqual(select(f,'完了グループのメドレーの請求書を確認').indices,[0]);});
test('explicit artist/project, history and open song retain access to completed work',()=>{const f=fixture();assert.deepEqual(select(f,'完了グループのメドレーを確認').indices,[0]);assert.deepEqual(select(f,'完了グループ 秋公演のメドレーを修正').indices,[0]);assert.deepEqual(select(f,'メドレーの履歴を確認').indices,[0,1]);assert.deepEqual(select(f,'メドレーを確認','old').indices,[0]);assert.deepEqual(select(f,'メドレーを確認','deleted').indices,[]);});
test('artist short names can explicitly identify completed work',()=>{const f=fixture();f.songs[0].artist='OCHA NORMA';f.songs[1].artist='ロージークロニクル';assert.deepEqual(select(f,'OCHAのメドレーを確認').indices,[0]);assert.deepEqual(select(f,'ロージーのメドレーを確認').indices,[1]);});
test('two unfinished namesakes stay ambiguous instead of using array order',()=>{const f=fixture();f.songs[0].stages.make.done=false;const r=select(f,'メドレーは今日中です');assert.deepEqual(r.indices,[0,1]);assert.equal(r.selected,-1);});
test('overlapping names preserve explicitly named multiple songs',()=>{const f=fixture();f.songs[0].title='メドレー２';f.songs[0].stages.make.done=false;assert.deepEqual(select(f,'メドレー２を確認').indices,[0]);assert.deepEqual(select(f,'メドレーとメドレー２を確認').indices,[0,1]);});
test('a completion report does not reopen old namesakes; genuinely historical requests can',()=>{const f=fixture();assert.equal(select(f,'メドレーの作成が終わったので納品します').selected,1);assert.deepEqual(select(f,'メドレーは両方どうなっていますか').indices,[0,1]);});
test('a follow-up artist correction replaces the prior artist while keeping the subject',()=>{const f=fixture(),r=P.consultationTargets(f.songs,f.projects,'完了グループの方です','global',today,'進行中グループのメドレーを確認');assert.deepEqual(r.indices,[0]);assert.equal(r.selected,0);});
test('general overview still includes unfinished administration for completed music',()=>{const f=fixture();f.songs[0].credits=[{id:'player',name:'演奏者',parts:['Guitar']}];f.songs[0].invoiceTracking=true;assert.deepEqual(select(f,'今の作業を整理して').indices,[0,1]);});
const source=fs.readFileSync(require.resolve('../app.js'),'utf8');
function context(f=fixture()){const c={ShinkouProduction:P,ShinkouWorkflow:W,ShinkouCore:C,S:{...f,masters:{},assistantRules:[]},D:{today:()=>today},songTitle:s=>s.title,projTitle:p=>p.custom,isShow:p=>p.mode==='live',sortOf:()=>'',songHasMV:()=>false,stages:C.activeStages,stg:(s,k)=>s.stages[k],isMulti:()=>false,ANCHOR_KEYS:[],rulesForSong:()=>[],conversationScope:()=> 'global',aiSelectModel:()=>({model:'test'})};vm.createContext(c);for(const [a,b]of [['function aiCtx(','const AI_SYS='],['async function aiCall(','/* opの対象']])vm.runInContext(source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a))),c);return c;}
test('actual AI payload omits completed namesakes and sends only stable song indices',async()=>{const c=context();let sent;c.aiChat=async msgs=>{sent=JSON.parse(msgs[0].content.split('データ:\n')[1].split('\n\n入力:')[0]);return {out:{ops:[],ans:'進行中グループのメドレーとして確認します'},tx:'{}'};};const result=await c.aiCall('メドレーは担当者さん待ちです。今日中に来る予定です。','global');assert.deepEqual(sent.songs.map(s=>s.i),[1]);assert.equal(sent.targeting.selected_song,1);assert.equal(result.out.targeting.selected_song,1);assert.equal(sent.songs[0].production_complete,false);assert.ok(sent.songs[0].candidate_tasks.includes('stage:make'));});
test('completed tasks remain facts in context but never appear among open task candidates',()=>{const f=fixture();f.songs[1].stages.mix.done=true;const c=context(f),ctx=c.aiCtx('global','メドレーを確認'),s=ctx.songs[0];assert.ok(s.completed_tasks.includes('stage:mix'));assert.equal(s.candidate_tasks.includes('stage:mix'),false);const stage=s.stages.find(st=>typeof st==='object'&&ctx.stage_catalog[st.ref].k==='mix');assert.equal(stage.done,1);});
test('filtered context retains release targets inherited from the project',()=>{const f=fixture();f.songs[1].use='master';f.projects[1].release='2027-02-24';const c=context(f),s=c.aiCtx('current','今後の予定').songs[0];assert.equal(s.targets.master,'2027-01-24');});
