'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {IDBFactory}=require('fake-indexeddb'),Security=require('../security.js');
const state=()=>({songs:[{id:'s',title:'確認曲',key:'C major'}],projects:[],settings:{sync:{token:'sync-secret',repo:'old'},gh:{token:'publish-secret'},ai:{key:'ai-secret',hist:[{q:'質問'}]},connections:{refresh_token:'refresh-secret'}}});
test('portable export removes nested credentials without changing songs or stored data',()=>{const original=state(),copy=Security.portable(original);assert.doesNotMatch(JSON.stringify(copy),/sync-secret|publish-secret|ai-secret|refresh-secret/);assert.equal(copy.songs[0].key,'C major');assert.equal(original.settings.sync.token,'sync-secret')});
test('import cannot replace this device credentials or sync destination',()=>{const imported=Security.imported(state(),{sync:{token:'local',repo:'private'},ai:{key:'local-ai'}});assert.equal(imported.settings.sync.token,'local');assert.equal(imported.settings.sync.repo,'private');assert.equal(imported.settings.ai.key,'local-ai');assert.equal(imported.settings.gh,undefined)});
test('prototype pollution and malformed data are rejected',()=>{const cleaned=Security.clean(JSON.parse('{"__proto__":{"polluted":true},"constructor":{"prototype":{"x":1}},"ok":1}'));assert.deepEqual(cleaned,{ok:1});assert.equal({}.polluted,undefined);assert.throws(()=>Security.validState({songs:[{id:'a'},{id:'a'}],projects:[]}));assert.throws(()=>Security.repoConfig({owner:'x',repo:'y',path:'../private'}))});
test('migration encrypts state, previous versions, sync base and all backups',async()=>{const entries=['state','state_prev','syncbase','bk:1','bkd:2026-09-24'].map(k=>[k,state()]);const plan=await Security.planRekey(entries,{newPin:'long test password'});assert.equal(plan.entries.length,5);for(const [,rec]of plan.entries){assert.equal(rec.enc,1);assert.equal(rec.iterations,600000);assert.doesNotMatch(JSON.stringify(rec),/sync-secret|確認曲/);assert.deepEqual(await Security.unpack(rec,plan.key),state())}const tampered={...plan.entries[0][1],data:plan.entries[0][1].data.slice(0,-4)+'AAAA'};await assert.rejects(Security.unpack(tampered,plan.key))});
test('old encrypted records rekey without losing backups; wrong password makes no changes',async()=>{const salt=Security.b64(crypto.getRandomValues(new Uint8Array(16))),key=await Security.keyFor('old password',salt,250000);const rec=await Security.pack(state(),key,salt,250000);delete rec.iterations;const entries=[['state',rec],['bk:old',state()]],before=structuredClone(entries);await assert.rejects(Security.planRekey(entries,{pin:'wrong',newPin:'new password'}));assert.deepEqual(entries,before);const plan=await Security.planRekey(entries,{pin:'old password',newPin:'new password'});for(const [,row]of plan.entries)assert.deepEqual(await Security.unpack(row,plan.key),state())});
function storage(){const source=fs.readFileSync(require.resolve('../app.js'),'utf8'),context={indexedDB:new IDBFactory(),ShinkouSecurity:Security,ShinkouServer:{enabled:false},crypto,TextEncoder,TextDecoder,btoa,atob,location:{pathname:'/',search:''}};vm.createContext(context);vm.runInContext("let CK=null,CKsalt=null,CKiterations=600000,encOn=false,securityChanging=false;"+source.slice(source.indexOf('function idb()'),source.indexOf('let sT=null')),context);context.setKey=(salt)=>vm.runInContext('CK={};CKsalt='+JSON.stringify(salt)+';CKiterations=600000',context);return context}
test('IndexedDB migration is atomic and detects a concurrent edit',async()=>{const c=storage();await c.kvPut('state',state());await c.kvPut('bk:1',state());const before=await c.storageEntries();await c.kvPut('state',{...state(),at:42});await assert.rejects(c.replaceStorageAtomically(before,before.map(([k])=>[k,{enc:1,salt:'new',iterations:600000}])));assert.equal((await c.kvGet('state')).at,42);assert.equal((await c.kvGet('bk:1')).enc,undefined)});
test('stale tab cannot overwrite encrypted state or create plaintext backups after rekey',async()=>{const c=storage();await c.kvPut('state',state());const before=await c.storageEntries(),encrypted={enc:1,salt:'new-salt',iterations:600000};await c.replaceStorageAtomically(before,[['state',encrypted]]);await assert.rejects(c.kvPut('state',state()));await assert.rejects(c.kvPut('bk:bad',state()));assert.equal((await c.kvGet('state')).enc,1);assert.equal(await c.kvGet('bk:bad'),undefined);c.setKey('new-salt');await c.kvPut('state',{...encrypted,data:'new'});assert.equal((await c.kvGet('state')).data,'new')});
test('encryption can be enabled before the first save',async()=>{const c=storage();await c.replaceStorageAtomically([],[],'first:600000');c.setKey('first');await c.kvPut('state',{enc:1,salt:'first',iterations:600000});assert.equal((await c.kvGet('state')).enc,1)});
