'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createApp}=require('../server/app.cjs');
const ORIGIN='https://shinkou.example',BASE_ENV={PUBLIC_ORIGIN:ORIGIN,SESSION_SECRET:'test-only-session-secret-not-for-production',GOOGLE_CLIENT_ID:'test.apps.googleusercontent.com',OWNER_EMAILS:'owner@gmail.com',EDITOR_EMAILS:'editor@gmail.com',VIEWER_EMAILS:'viewer@gmail.com',GITHUB_TOKEN:'test-github-key',OPENAI_API_KEY:'test-openai-key',DROPBOX_APP_KEY:'test-dropbox',DATA_OWNER:'owner',DATA_REPO:'private'};
const data=()=>({v:1,songs:[{id:'s',title:'確認曲',dropboxUrl:'https://www.dropbox.com/scl/fo/test',note:'private',workflow:{},invoiceItems:[]}],projects:[],templates:[],settings:{sync:{token:'should-never-leak'}},_serverAudit:[]});
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
async function fixture(t,overrides={}){let state=data(),sha='original',identity={},calls=[],publicRepo=false,scope='files.metadata.read';const env={...BASE_ENV,...overrides};
 const external=async(url,options={})=>{calls.push({url,options});if(url==='https://api.github.com/repos/owner/private')return json({private:!publicRepo});if(url.startsWith('https://api.github.com/repos/owner/private/contents/')){const file=new URL(url).pathname.split('/contents/')[1];if(options.method==='PUT'){const body=JSON.parse(options.body);if(file==='data.json'){state=JSON.parse(Buffer.from(body.content,'base64'));sha='updated'}return json({})}if(file==='data.json')return json({content:Buffer.from(JSON.stringify(state)).toString('base64'),sha});return json({},404)}if(url.startsWith('https://api.openai.com/'))return json({id:'response',output:[]});if(url.endsWith('/oauth2/token'))return json({access_token:'test-dropbox-token',scope,expires_in:14400});if(url.endsWith('/files/list_folder'))return json({entries:[{name:'demo.wav'}],has_more:false});throw Error('unexpected request '+url)};
 const app=createApp(env,{fetch:external,verify:async()=>identity}),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;
 const request=(route,options={})=>fetch(base+route,{redirect:'manual',...options,headers:{Origin:ORIGIN,'Content-Type':'application/json',...options.headers}});
 async function login(email='owner@gmail.com',extra={}){const challenge=await request('/api/auth/challenge'),{nonce}=await challenge.json();identity={sub:email,email,email_verified:true,nonce,...extra};const loginCookie=challenge.headers.getSetCookie()[0].split(';')[0];const response=await request('/api/auth/login',{method:'POST',headers:{Cookie:loginCookie},body:JSON.stringify({credential:'verified-by-test-double'})});const cookie=response.headers.getSetCookie().find(x=>x.startsWith('__Host-shinkou='))?.split(';')[0];const session=cookie?await(await request('/api/session',{headers:{Cookie:cookie}})).json():null;return {response,cookie,loginCookie,session,headers:{Cookie:cookie,'X-Shinkou-CSRF':session?.csrf}}}
 return {request,login,calls,get state(){return state},setPublic:()=>publicRepo=true,setScope:value=>scope=value};
}
test('unconfigured and unauthenticated servers never expose production data',async t=>{const f=await fixture(t,{GOOGLE_CLIENT_ID:''});assert.equal((await f.request('/api/data')).status,503);assert.equal(f.calls.length,0);for(const p of ['/server/app.cjs','/.env','/package.json'])assert.equal((await f.request(p)).status,404);const page=await f.request('/');assert.match(page.headers.get('content-security-policy'),/default-src 'self'/);assert.match(page.headers.get('cache-control'),/no-store/)});
test('Google identity must be verified, allowlisted, and tied to a one-use challenge',async t=>{const f=await fixture(t);assert.equal((await f.request('/api/data')).status,401);for(const [email,extra]of [['stranger@gmail.com',{}],['owner@gmail.com',{email_verified:false}],['owner@gmail.com',{nonce:'wrong'}]])assert.equal((await f.login(email,extra)).response.status,403);const auth=await f.login();assert.equal(auth.response.status,200);assert.match(auth.response.headers.getSetCookie().join(),/HttpOnly/);assert.match(auth.response.headers.getSetCookie().join(),/Secure/);assert.equal((await f.request('/api/auth/login',{method:'POST',headers:{Cookie:auth.loginCookie},body:'{"credential":"replay"}'})).status,401);assert.doesNotMatch(JSON.stringify(auth.session),/test-github-key|test-openai-key|test-dropbox-token/)});
test('CSRF, exact origin, role checks and cookie integrity guard all writes',async t=>{const f=await fixture(t),owner=await f.login();const payload=JSON.stringify({data:data(),sha:'original'});assert.equal((await f.request('/api/data',{method:'PUT',headers:{Cookie:owner.cookie},body:payload})).status,403);assert.equal((await f.request('/api/data',{method:'PUT',headers:{...owner.headers,Origin:'https://evil.example'},body:payload})).status,403);assert.equal((await f.request('/api/data',{method:'PUT',headers:{...owner.headers,'Sec-Fetch-Site':'cross-site'},body:payload})).status,403);assert.equal((await f.request('/api/session',{headers:{Cookie:owner.cookie+'tampered'}})).status,401);const viewer=await f.login('viewer@gmail.com');assert.equal((await f.request('/api/data',{method:'PUT',headers:viewer.headers,body:payload})).status,403);assert.equal((await f.request('/api/backups',{headers:viewer.headers})).status,403);assert.equal(f.calls.length,0)});
test('private repo required, data revision conflicts cannot overwrite, exports omit settings',async t=>{const f=await fixture(t),auth=await f.login();const value=await(await f.request('/api/data',{headers:auth.headers})).json();assert.equal(value.json.settings,undefined);assert.equal(value.json._serverAudit,undefined);assert.equal((await f.request('/api/data',{method:'PUT',headers:auth.headers,body:JSON.stringify({data:data(),sha:'stale'})})).status,409);assert.equal(f.calls.some(c=>c.options.method==='PUT'),false);const saved=await f.request('/api/data',{method:'PUT',headers:auth.headers,body:JSON.stringify({data:data(),sha:'original'})});assert.equal(saved.status,200);assert.equal(f.state.settings,undefined);assert.equal(f.state._serverAudit[0].by,'owner@gmail.com');assert.ok(f.calls.some(c=>/snapshots\/\d{4}-\d{2}-\d{2}\.json/.test(c.url)&&c.options.method==='PUT'))});
test('public repository blocks both read and write',async t=>{const f=await fixture(t),auth=await f.login();f.setPublic();assert.equal((await f.request('/api/data',{headers:auth.headers})).status,503);assert.equal((await f.request('/api/data',{method:'PUT',headers:auth.headers,body:JSON.stringify({data:data(),sha:'original'})})).status,503);assert.equal(f.calls.some(c=>c.options.method==='PUT'),false)});
test('AI retains JSON instructions, constrains model and never accepts client keys',async t=>{const f=await fixture(t),auth=await f.login();const response=await f.request('/api/ai',{method:'POST',headers:auth.headers,body:JSON.stringify({body:{model:'gpt-5.4',instructions:'JSONだけを返す',input:[{role:'user',content:'確認'}],store:true,max_output_tokens:999999,api_key:'malicious'}})});assert.equal(response.status,200);const sent=f.calls.find(c=>c.url.endsWith('/responses')),payload=JSON.parse(sent.options.body);assert.equal(payload.instructions,'JSONだけを返す');assert.equal(payload.text.format.type,'json_object');assert.equal(payload.store,false);assert.equal(payload.max_output_tokens,16000);assert.equal(payload.api_key,undefined);assert.equal(sent.options.headers.Authorization,'Bearer test-openai-key');assert.equal((await f.request('/api/ai',{method:'POST',headers:auth.headers,body:'{"model":"unapproved"}'})).status,400)});
test('Dropbox OAuth uses metadata-only PKCE bound to session and saved folder',async t=>{const f=await fixture(t),auth=await f.login();const start=await(await f.request('/api/dropbox/start',{method:'POST',headers:auth.headers,body:'{}'})).json(),url=new URL(start.url);assert.equal(url.searchParams.get('scope'),'files.metadata.read');assert.equal(url.searchParams.get('code_challenge_method'),'S256');const state=url.searchParams.get('state');assert.equal((await f.request('/oauth/dropbox/callback?state='+state+'&code=test',{headers:auth.headers})).status,302);assert.equal((await f.request('/oauth/dropbox/callback?state='+state+'&code=test',{headers:auth.headers})).status,400);assert.equal((await f.request('/api/dropbox/list',{method:'POST',headers:auth.headers,body:JSON.stringify({url:'https://www.dropbox.com/scl/fo/other'})})).status,403);const response=await f.request('/api/dropbox/list',{method:'POST',headers:auth.headers,body:JSON.stringify({url:data().songs[0].dropboxUrl})});assert.equal(response.status,200);assert.deepEqual((await response.json()).items,[{name:'demo.wav'}])});
test('Dropbox refuses excessive scope and logout invalidates current session',async t=>{const f=await fixture(t),auth=await f.login();f.setScope('files.metadata.read files.content.read');const start=await(await f.request('/api/dropbox/start',{method:'POST',headers:auth.headers,body:'{}'})).json(),state=new URL(start.url).searchParams.get('state');assert.equal((await f.request('/oauth/dropbox/callback?state='+state+'&code=test',{headers:auth.headers})).status,403);assert.equal((await f.request('/api/logout',{method:'POST',headers:auth.headers,body:'{}'})).status,200);assert.equal((await f.request('/api/session',{headers:auth.headers})).status,401)});
